#██╗    ██╗██╗███╗   ██╗██████╗  ██████╗ ██╗    ██╗██████╗ ██╗   ██╗██╗     ███████╗███████╗
#██║    ██║██║████╗  ██║██╔══██╗██╔═══██╗██║    ██║██╔══██╗██║   ██║██║     ██╔════╝██╔════╝
#██║ █╗ ██║██║██╔██╗ ██║██║  ██║██║   ██║██║ █╗ ██║██████╔╝██║   ██║██║     █████╗  ███████╗
#██║███╗██║██║██║╚██╗██║██║  ██║██║   ██║██║███╗██║██╔══██╗██║   ██║██║     ██╔══╝  ╚════██║
#╚███╔███╔╝██║██║ ╚████║██████╔╝╚██████╔╝╚███╔███╔╝██║  ██║╚██████╔╝███████╗███████╗███████║
# ╚══╝╚══╝ ╚═╝╚═╝  ╚═══╝╚═════╝  ╚═════╝  ╚══╝╚══╝ ╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚══════╝╚══════
windowrule=opacity 1 1,float on, 
#windowrule = float, class:^(Rofi|rofi)$

# Rofi
windowrule = match:class ^(Rofi|rofi)$, float on

# Blueman
windowrule = match:class ^(blueman-manager)$, float on, size 800 500

# imv
windowrule = match:class ^(imv)$, float on

# Yad
windowrule = match:class ^(Yad|yad)$, float on, size 880 750

# Pavucontrol
windowrule = match:class ^(pavucontrol|org\.pulseaudio\.pavucontrol|com\.saivert\.pwvucontrol)$, float on

# Honkers Railway Launcher
windowrule = match:class ^(moe\.launcher\.the-honkers-railway-launcher)$, float on, center on

########################################
# xwaylandvideobridge fixes
########################################

windowrule = match:class ^(xwaylandvideobridge)$, opacity 0.0
windowrule = match:class ^(xwaylandvideobridge)$, no_anim on
windowrule = match:class ^(xwaylandvideobridge)$, no_initial_focus on
windowrule = match:class ^(xwaylandvideobridge)$, max_size 1 1
windowrule = match:class ^(xwaylandvideobridge)$, no_blur on
